### ISSUE TITLE
Lootr chests with nothing in them

### ISSUE THREAD

**Issue by XVPhoenixVII** [noobanidus/Lootr#151]
title says it all, im not sure whats the reason for this, i even spawned in a Lootr chest to make sure and nothing was inside the chest, even when i found a generated chest in a village, nothing was inside

**Comment by XVPhoenixVII** [comment]
here is my log
[latest.log](https://github.com/noobanidus/Lootr/files/9944811/latest.log)

**Comment by noobanidus** [comment]
Some of it looks to be an issue with Tetra based on the errors in the log:

```java
java.lang.RuntimeException: Attempted to add a duplicate pool to loot table: tetra:chests/bastion_other_extended
	at net.minecraft.world.level.storage.loot.LootTable.addPool(LootTable.java:218) ~[client-1.18.2-20220404.173914-srg.jar%23296!/:?]
	at se.mickelus.tetra.items.scroll.ScrollDrops.onLootTableLoad(ScrollDrops.java:32) ~[tetra-1.18.2-4.10.1.jar%23258!/:4.10.1]
	at net.minecraftforge.eventbus.ASMEventHandler_1700_ScrollDrops_onLootTableLoad_LootTableLoadEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!/:?]
```

Further down in the log:

```
[18:19:42] [Server thread/ERROR]: Unable to fill loot chest in ResourceKey[minecraft:dimension / minecraft:overworld] at BlockPos{x=1401, y=122, z=302} as the loot table 'kaisyn:village/village_birch_forest_house' couldn't be resolved! Please search the loot table in `latest.log` to see if there are errors in loading.
[18:21:14] [Server thread/ERROR]: Unable to fill loot chest in ResourceKey[minecraft:dimension / minecraft:overworld] at BlockPos{x=1408, y=120, z=301} as the loot table 'minecraft:loot_table' couldn't be resolved! Please search the loot table in `latest.log` to see if there are errors in loading.
```

1. The manually-created chest doesn't have a valid loot table. You can just use the `/lootr chest` command to spawn with a random loot table.
2. The relevant village loot table has been corrupted.

This definitely appears to be an issue with other mods rather than with Lootr.
