### ISSUE TITLE
Latest 1.16.5 Lootr mod forge

### ISSUE THREAD

**Issue by Orangejewce92** [noobanidus/Lootr#157]
I've been recieving a bunch of tickets for players when creating a new world with this mod that more than 75% of chests are not open-able. Is there a config or setting that's new that's doing this? Or a permission they might need?

**Comment by Orangejewce92** [comment]
Seems to be only on servers this is an issue. Single player no issue.

**Comment by Orangejewce92** [comment]
I think the issue may lie within your .46 version. When on mod lists it's displaying at .45 but it is indeed the .46 download. And there's some sort of mismatch issue possibly.

Again this is on 1.16.5

**Comment by Orangejewce92** [comment]
`[18:07:25] [Server thread/FATAL]: Error executing task on Server
java.lang.IllegalArgumentException: Missing required parameters: [<parameter minecraft:origin>]
	at net.minecraft.loot.LootContext$Builder.func_216022_a(LootContext.java:215) ~[?:?]
	at com.infamous.dungeons_gear.utilties.LootTableHelper.copyLootContextWithNewQueryID(LootTableHelper.java:60) ~[?:1.16.5-3.2.1]
	at com.infamous.dungeons_gear.utilties.LootTableHelper.generateItemStacks(LootTableHelper.java:47) ~[?:1.16.5-3.2.1]
	at com.infamous.dungeons_gear.loot.GlobalLootModifier$DungeonsLootAdditions.doApply(GlobalLootModifier.java:59) ~[?:1.16.5-3.2.1]
	at net.minecraftforge.common.loot.LootModifier.apply(LootModifier.java:39) ~[?:?]
	at net.minecraftforge.common.ForgeHooks.modifyLoot(ForgeHooks.java:1287) ~[?:?]
	at net.minecraft.loot.LootTable.func_216113_a(LootTable.java:86) ~[?:?]
	at com.teamremastered.endrem.utils.LootInjector$LootInjectionModifier.doApply(LootInjector.java:31) ~[?:5.0.3-R-1.16.5]
	at net.minecraftforge.common.loot.LootModifier.apply(LootModifier.java:39) ~[?:?]
	at net.minecraftforge.common.ForgeHooks.modifyLoot(ForgeHooks.java:1287) ~[?:?]
	at net.minecraft.loot.LootTable.func_216113_a(LootTable.java:86) ~[?:?]
	at net.minecraft.loot.LootTable.func_216118_a(LootTable.java:106) ~[?:?]
	at noobanidus.mods.lootr.block.tile.LootrChestTileEntity.fillWithLoot(LootrChestTileEntity.java:115) ~[?:0.1.15.46]
	at noobanidus.mods.lootr.util.ChestUtil$$Lambda$40135/1325353127.fillWithLoot(Unknown Source) ~[?:?]
	at noobanidus.mods.lootr.data.ChestData.createInventory(ChestData.java:149) ~[?:0.1.15.46]
	at noobanidus.mods.lootr.data.DataStorage.getInventory(DataStorage.java:164) ~[?:0.1.15.46]
	at noobanidus.mods.lootr.util.ChestUtil.handleLootChest(ChestUtil.java:123) ~[?:0.1.15.46]
	at noobanidus.mods.lootr.block.LootrChestBlock.func_225533_a_(LootrChestBlock.java:72) ~[?:0.1.15.46]
	at net.minecraft.block.AbstractBlock$AbstractBlockState.func_227031_a_(AbstractBlock.java:640) ~[?:?]
	at net.minecraft.server.management.PlayerInteractionManager.func_219441_a(PlayerInteractionManager.java:338) ~[?:?]
	at net.minecraft.network.play.ServerPlayNetHandler.func_184337_a(ServerPlayNetHandler.java:958) ~[?:?]
	at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(SourceFile:36) ~[?:?]
	at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(SourceFile:10) ~[?:?]
	at net.minecraft.network.PacketThreadUtil.func_225383_a(SourceFile:21) ~[?:?]
	at net.minecraft.network.PacketThreadUtil$$Lambda$37924/2036172487.run(Unknown Source) ~[?:?]
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(SourceFile:144) [?:?]
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) [?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:734) [?:?]
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:159) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(SourceFile:118) [?:?]
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:717) [?:?]
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:711) [?:?]
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(SourceFile:103) [?:?]
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:696) [?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:646) [?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) [?:?]
	at net.minecraft.server.MinecraftServer$$Lambda$35166/39813723.run(Unknown Source) [?:?]`

**Comment by Orangejewce92** [comment]
so its definitely not a lootr mod issue. its a mod i have in my pack thats causing the issue. im trying to figure it out but struggling here!
