### ISSUE TITLE
Receiver class noobanidus.mods.lootr.data.SpecialChestInventory does not define or inherit an implementation of the resolved method 'abstract void onOpen

### ISSUE THREAD

**Issue by UrbanSide** [noobanidus/Lootr#217]
Minecraft 1.18.2 Server Mohist
```
`Time: 9/17/23, 1:21 PM
Description: Exception in server tick loop

java.lang.AbstractMethodError: Receiver class noobanidus.mods.lootr.data.SpecialChestInventory does not define or inherit an implementation of the resolved method 'abstract void onOpen(org.bukkit.craftbukkit.v1_18_R2.entity.CraftHumanEntity)' of interface net.minecraft.world.Container.
	at net.minecraft.world.inventory.AbstractContainerMenu.transferTo(AbstractContainerMenu.java:90) ~[server-1.18.2-20220404.173914-srg.jar%23364!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flytre_lib.mixins.json:storage.upgrade.ScreenHandlerMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.ContainerAccess,pl:mixin:APP:valkyrienskies-common.mixins.json:feature.screen_distance_check.MixinScreenHandler,pl:mixin:APP:placebo.mixins.json:AbstractContainerMenuInvoker,pl:mixin:APP:relics.mixins.json:MixinAbstractContainerMenu,pl:mixin:A}
	at org.bukkit.craftbukkit.v1_18_R2.event.CraftEventFactory.callInventoryOpenEvent(CraftEventFactory.java:1183) ~[forge-1.18.2-40.2.10-universal.jar%23369!/:?] {re:classloading}
	at net.minecraft.server.level.ServerPlayer.m_5893_(ServerPlayer.java:1288) ~[server-1.18.2-20220404.173914-srg.jar%23364!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:yungsapi.mixins.json:ServerPlayerEntityTickMixin,pl:mixin:APP:flytre_lib.mixins.json:storage.upgrade.ServerPlayerEntityMixin,pl:mixin:APP:botania_xplat.mixins.json:MixinServerPlayer,pl:mixin:APP:the_bumblezone.mixins.json:entities.ServerPlayerMixin,pl:mixin:APP:ars_nouveau.mixins.json:camera.ANServerPlayerMixin,pl:mixin:APP:antiqueatlas-common.mixins.json:MixinPlayerEntityDeath,pl:mixin:APP:byg.mixins.json:common.entity.MixinServerPlayer,pl:mixin:APP:mannequins-common.mixins.json:ServerPlayerAccessor,pl:mixin:APP:valkyrienskies-common.mixins.json:feature.bed_fix.MixinServerPlayer,pl:mixin:APP:valkyrienskies-common.mixins.json:server.command.level.MixinServerPlayer,pl:mixin:APP:netherportalfix.mixins.json:ServerPlayerMixin,pl:mixin:APP:netherportalfix.mixins.json:ForgeServerPlayerMixin,pl:mixin:APP:betterdeserttemples.mixins.json:ServerPlayerTickMixin,pl:mixin:APP:pollen-common.mixins.json:ServerPlayerMixin,pl:mixin:APP:tombstone.mixins.json:ServerPlayerMixin,pl:mixin:A,re:mixin,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at noobanidus.mods.lootr.util.ChestUtil.handleLootChest(ChestUtil.java:137) ~[lootr-1.18.2-0.3.25.63.jar%23242!/:0.3.25.63] {re:classloading}
	at noobanidus.mods.lootr.block.LootrBarrelBlock.m_6227_(LootrBarrelBlock.java:59) ~[lootr-1.18.2-0.3.25.63.jar%23242!/:0.3.25.63] {re:classloading}
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60664_(BlockBehaviour.java:697) ~[server-1.18.2-20220404.173914-srg.jar%23364!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:forgeendertech:coremod,xf:fml:libx:random_tick_block,re:classloading,pl:accesstransformer:B,xf:fml:forgeendertech:coremod,xf:fml:libx:random_tick_block,pl:mixin:APP:modernfix-common.mixins.json:bugfix.chunk_deadlock.BlockStateBaseMixin,pl:mixin:APP:kubejs-common.mixins.json:BlockStateBaseMixin,pl:mixin:APP:notreepunching.common.mixins.json:AbstractBlockStateAccessor,pl:mixin:APP:passablefoliage.mixins.json:BlockStateMixin,pl:mixin:APP:starlight.mixins.json:common.blockstate.BlockStateBaseMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.block.AccessBlockStateBase,pl:mixin:APP:immersiveengineering.mixins.json:coremods.AbstractBlockStateMixin,pl:mixin:APP:byg.mixins.json:common.block.MixinBlockBehaviourBlockStateBase,pl:mixin:APP:ferritecore.blockstatecache.mixin.json:BlockStateBaseMixin,pl:mixin:A}
	at net.minecraft.server.level.ServerPlayerGameMode.m_7179_(ServerPlayerGameMode.java:469) ~[server-1.18.2-20220404.173914-srg.jar%23364!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:libx:interact,re:computing_frames,pl:accesstransformer:B,xf:fml:libx:interact,re:classloading,pl:accesstransformer:B,xf:fml:libx:interact,pl:mixin:A}
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_6371_(ServerGamePacketListenerImpl.java:1417) ~[server-1.18.2-20220404.173914-srg.jar%23364!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A,re:mixin,pl:accesstransformer:B}
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.m_5797_(ServerboundUseItemOnPacket.java:30) ~[server-1.18.2-20220404.173914-srg.jar%23364!/:?] {re:classloading}
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.m_5797_(ServerboundUseItemOnPacket.java:8) ~[server-1.18.2-20220404.173914-srg.jar%23364!/:?] {re:classloading}
	at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:24) ~[server-1.18.2-20220404.173914-srg.jar%23364!/:?] {re:classloading}
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.18.2-20220404.173914-srg.jar%23364!/:?] {re:classloading,re:mixin}
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[server-1.18.2-20220404.173914-srg.jar%23364!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.18.2-20220404.173914-srg.jar%23364!/:?] {re:mixin,re:computing_frames,re:classloading}
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:920) ~[server-1.18.2-20220404.173914-srg.jar%23364!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:flytre_lib.mixins.json:base.MinecraftServerMixin,pl:mixin:APP:flytre_lib.mixins.json:config.MinecraftServerMixin,pl:mixin:APP:fastload.mixins.json:server.MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:APP:globaldataandresourcepacks.mixins.json:PackConfigurationMixin,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:valkyrienskies-common.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:167) ~[server-1.18.2-20220404.173914-srg.jar%23364!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:flytre_lib.mixins.json:base.MinecraftServerMixin,pl:mixin:APP:flytre_lib.mixins.json:config.MinecraftServerMixin,pl:mixin:APP:fastload.mixins.json:server.MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:APP:globaldataandresourcepacks.mixins.json:PackConfigurationMixin,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:valkyrienskies-common.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[server-1.18.2-20220404.173914-srg.jar%23364!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:903) ~[server-1.18.2-20220404.173914-srg.jar%23364!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:flytre_lib.mixins.json:base.MinecraftServerMixin,pl:mixin:APP:flytre_lib.mixins.json:config.MinecraftServerMixin,pl:mixin:APP:fastload.mixins.json:server.MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:APP:globaldataandresourcepacks.mixins.json:PackConfigurationMixin,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:valkyrienskies-common.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:897) ~[server-1.18.2-20220404.173914-srg.jar%23364!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:flytre_lib.mixins.json:base.MinecraftServerMixin,pl:mixin:APP:flytre_lib.mixins.json:config.MinecraftServerMixin,pl:mixin:APP:fastload.mixins.json:server.MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:APP:globaldataandresourcepacks.mixins.json:PackConfigurationMixin,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:valkyrienskies-common.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:116) ~[server-1.18.2-20220404.173914-srg.jar%23364!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:882) ~[server-1.18.2-20220404.173914-srg.jar%23364!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:flytre_lib.mixins.json:base.MinecraftServerMixin,pl:mixin:APP:flytre_lib.mixins.json:config.MinecraftServerMixin,pl:mixin:APP:fastload.mixins.json:server.MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:APP:globaldataandresourcepacks.mixins.json:PackConfigurationMixin,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:valkyrienskies-common.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:791) ~[server-1.18.2-20220404.173914-srg.jar%23364!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:flytre_lib.mixins.json:base.MinecraftServerMixin,pl:mixin:APP:flytre_lib.mixins.json:config.MinecraftServerMixin,pl:mixin:APP:fastload.mixins.json:server.MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:APP:globaldataandresourcepacks.mixins.json:PackConfigurationMixin,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:valkyrienskies-common.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:286) ~[server-1.18.2-20220404.173914-srg.jar%23364!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:flytre_lib.mixins.json:base.MinecraftServerMixin,pl:mixin:APP:flytre_lib.mixins.json:config.MinecraftServerMixin,pl:mixin:APP:fastload.mixins.json:server.MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:APP:globaldataandresourcepacks.mixins.json:PackConfigurationMixin,pl:mixin:APP:byg.mixins.json:access.MinecraftServerAccess,pl:mixin:APP:byg.mixins.json:server.MixinMinecraftServer,pl:mixin:APP:valkyrienskies-common.mixins.json:server.MixinMinecraftServer,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) [?:?] {re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin}`
```

**Comment by noobanidus** [comment]
This is an issue with Mohist/CraftBukkit, not Lootr. Unfortunately this isn't something I can control, as they're looking for their own method interface in a `Container`. 

This is related to #86 but cannot be solved in the same way as that was a conflict in naming.

The developer of Magma commented on that issue saying that they had resolved it on their end; perhaps Magma might be an option for you instead of Mohist?

**Comment by UrbanSide** [comment]
> This is an issue with Mohist/CraftBukkit, not Lootr. Unfortunately this isn't something I can control, as they're looking for their own method interface in a `Container`.
> 
> This is related to #86 but cannot be solved in the same way as that was a conflict in naming.
> 
> The developer of Magma commented on that issue saying that they had resolved it on their end; perhaps Magma might be an option for you instead of Mohist?

There are other errors in magma, alas) Sorry I was wrong)

**Comment by noobanidus** [comment]
They might be open to improving compatibility with Lootr however.

**Comment by UrbanSide** [comment]
![image](https://github.com/noobanidus/Lootr/assets/26259129/24c265cb-4d42-4186-8412-906292fd7780)
no, I’m talking about the fact that on magma I don’t even get to the point of checking LOOTR :D I’ll go torture them, thanks)

**Comment by noobanidus** [comment]
> ![image](https://user-images.githubusercontent.com/26259129/268498907-24c265cb-4d42-4186-8412-906292fd7780.png) no, I’m talking about the fact that on magma I don’t even get to the point of checking LOOTR :D I’ll go torture them, thanks)

That's a slightly disturbing looking traceback; that said, the mod that is causing the issue appears to be "Horde Hoard", which is an MCreator mod. Removing that might also help with things.

**Comment by UrbanSide** [comment]
> > ![image](https://user-images.githubusercontent.com/26259129/268498907-24c265cb-4d42-4186-8412-906292fd7780.png) no, I’m talking about the fact that on magma I don’t even get to the point of checking LOOTR :D I’ll go torture them, thanks)
> 
> That's a slightly disturbing looking traceback; that said, the mod that is causing the issue appears to be "Horde Hoard", which is an MCreator mod. Removing that might also help with things.

thx i remove https://www.curseforge.com/minecraft/mc-mods/enhanced-hordes and server seems to have gone to launch on magma.

**Sorry for bothering you unnecessarily)**
