### ISSUE TITLE
[1.20.1] Crash: Exception ticking world

### ISSUE THREAD

**Issue by lunofe** [noobanidus/Lootr#265]
# Description: Exception ticking world
```
java.lang.NullPointerException: Cannot invoke "java.util.UUID.equals(Object)" because the return value of "noobanidus.mods.lootr.data.SpecialChestInventory.getTileId()" is null
	at noobanidus.mods.lootr.block.entities.LootrBarrelBlockEntity$1.m_142718_(LootrBarrelBlockEntity.java:90) ~[lootr-1.20-0.7.31.76.jar%23272!/:0.7.31.76] {re:classloading}
	at net.minecraft.world.level.Level.m_260792_(Level.java:835) ~[server-1.20.1-20230612.114412-srg.jar%23316!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:lithium.mixins.json:alloc.chunk_random.WorldMixin,pl:mixin:APP:lithium.mixins.json:block.hopper.WorldMixin,pl:mixin:APP:lithium.mixins.json:entity.collisions.intersection.WorldMixin,pl:mixin:APP:lithium.mixins.json:util.block_entity_retrieval.WorldMixin,pl:mixin:APP:lithium.mixins.json:util.block_tracking.block_listening.WorldMixin,pl:mixin:APP:lithium.mixins.json:world.block_entity_ticking.sleeping.WorldMixin,pl:mixin:APP:lithium.mixins.json:world.chunk_access.WorldMixin,pl:mixin:APP:lithium.mixins.json:world.inline_block_access.WorldMixin,pl:mixin:APP:lithium.mixins.json:world.inline_height.WorldMixin,pl:mixin:A,re:mixin,pl:accesstransformer:B}
	at net.minecraft.world.level.entity.EntitySection.m_188348_(EntitySection.java:51) ~[server-1.20.1-20230612.114412-srg.jar%23316!/:?] {re:mixin,re:classloading,pl:mixin:APP:lithium.mixins.json:block.hopper.EntityTrackingSectionAccessor,pl:mixin:APP:lithium.mixins.json:chunk.entity_class_groups.EntityTrackingSectionAccessor,pl:mixin:APP:lithium.mixins.json:entity.collisions.unpushable_cramming.EntityTrackingSectionMixin,pl:mixin:APP:lithium.mixins.json:util.entity_movement_tracking.EntityTrackingSectionMixin,pl:mixin:APP:lithium.mixins.json:util.entity_section_position.EntityTrackingSectionMixin,pl:mixin:A}
	at net.minecraft.world.level.entity.EntitySectionStorage.m_260795_(EntitySectionStorage.java:126) ~[server-1.20.1-20230612.114412-srg.jar%23316!/:?] {re:mixin,re:classloading,pl:mixin:APP:lithium.mixins.json:entity.fast_retrieval.SectionedEntityCacheMixin,pl:mixin:APP:lithium.mixins.json:util.entity_movement_tracking.SectionedEntityCacheMixin,pl:mixin:APP:lithium.mixins.json:util.entity_section_position.SectionedEntityCacheMixin,pl:mixin:A}
	at net.minecraft.world.level.entity.EntitySectionStorage.consumeSection(EntitySectionStorage.java:589) ~[server-1.20.1-20230612.114412-srg.jar%23316!/:?] {re:mixin,re:classloading,pl:mixin:APP:lithium.mixins.json:entity.fast_retrieval.SectionedEntityCacheMixin,pl:mixin:APP:lithium.mixins.json:util.entity_movement_tracking.SectionedEntityCacheMixin,pl:mixin:APP:lithium.mixins.json:util.entity_section_position.SectionedEntityCacheMixin,pl:mixin:A}
	at net.minecraft.world.level.entity.EntitySectionStorage.forEachInColumn(EntitySectionStorage.java:579) ~[server-1.20.1-20230612.114412-srg.jar%23316!/:?] {re:mixin,re:classloading,pl:mixin:APP:lithium.mixins.json:entity.fast_retrieval.SectionedEntityCacheMixin,pl:mixin:APP:lithium.mixins.json:util.entity_movement_tracking.SectionedEntityCacheMixin,pl:mixin:APP:lithium.mixins.json:util.entity_section_position.SectionedEntityCacheMixin,pl:mixin:A}
	at net.minecraft.world.level.entity.EntitySectionStorage.handler$zec000$forEachInBox(EntitySectionStorage.java:562) ~[server-1.20.1-20230612.114412-srg.jar%23316!/:?] {re:mixin,re:classloading,pl:mixin:APP:lithium.mixins.json:entity.fast_retrieval.SectionedEntityCacheMixin,pl:mixin:APP:lithium.mixins.json:util.entity_movement_tracking.SectionedEntityCacheMixin,pl:mixin:APP:lithium.mixins.json:util.entity_section_position.SectionedEntityCacheMixin,pl:mixin:A}
	at net.minecraft.world.level.entity.EntitySectionStorage.m_188362_(EntitySectionStorage.java:54) ~[server-1.20.1-20230612.114412-srg.jar%23316!/:?] {re:mixin,re:classloading,pl:mixin:APP:lithium.mixins.json:entity.fast_retrieval.SectionedEntityCacheMixin,pl:mixin:APP:lithium.mixins.json:util.entity_movement_tracking.SectionedEntityCacheMixin,pl:mixin:APP:lithium.mixins.json:util.entity_section_position.SectionedEntityCacheMixin,pl:mixin:A}
	at net.minecraft.world.level.entity.EntitySectionStorage.m_261191_(EntitySectionStorage.java:126) ~[server-1.20.1-20230612.114412-srg.jar%23316!/:?] {re:mixin,re:classloading,pl:mixin:APP:lithium.mixins.json:entity.fast_retrieval.SectionedEntityCacheMixin,pl:mixin:APP:lithium.mixins.json:util.entity_movement_tracking.SectionedEntityCacheMixin,pl:mixin:APP:lithium.mixins.json:util.entity_section_position.SectionedEntityCacheMixin,pl:mixin:A}
	at net.minecraft.world.level.entity.LevelEntityGetterAdapter.m_142137_(LevelEntityGetterAdapter.java:48) ~[server-1.20.1-20230612.114412-srg.jar%23316!/:?] {re:classloading}
	at net.minecraft.world.level.Level.m_260826_(Level.java:834) ~[server-1.20.1-20230612.114412-srg.jar%23316!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:lithium.mixins.json:alloc.chunk_random.WorldMixin,pl:mixin:APP:lithium.mixins.json:block.hopper.WorldMixin,pl:mixin:APP:lithium.mixins.json:entity.collisions.intersection.WorldMixin,pl:mixin:APP:lithium.mixins.json:util.block_entity_retrieval.WorldMixin,pl:mixin:APP:lithium.mixins.json:util.block_tracking.block_listening.WorldMixin,pl:mixin:APP:lithium.mixins.json:world.block_entity_ticking.sleeping.WorldMixin,pl:mixin:APP:lithium.mixins.json:world.chunk_access.WorldMixin,pl:mixin:APP:lithium.mixins.json:world.inline_block_access.WorldMixin,pl:mixin:APP:lithium.mixins.json:world.inline_height.WorldMixin,pl:mixin:A,re:mixin,pl:accesstransformer:B}
	at net.minecraft.world.level.Level.m_261153_(Level.java:829) ~[server-1.20.1-20230612.114412-srg.jar%23316!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:lithium.mixins.json:alloc.chunk_random.WorldMixin,pl:mixin:APP:lithium.mixins.json:block.hopper.WorldMixin,pl:mixin:APP:lithium.mixins.json:entity.collisions.intersection.WorldMixin,pl:mixin:APP:lithium.mixins.json:util.block_entity_retrieval.WorldMixin,pl:mixin:APP:lithium.mixins.json:util.block_tracking.block_listening.WorldMixin,pl:mixin:APP:lithium.mixins.json:world.block_entity_ticking.sleeping.WorldMixin,pl:mixin:APP:lithium.mixins.json:world.chunk_access.WorldMixin,pl:mixin:APP:lithium.mixins.json:world.inline_block_access.WorldMixin,pl:mixin:APP:lithium.mixins.json:world.inline_height.WorldMixin,pl:mixin:A,re:mixin,pl:accesstransformer:B}
	at net.minecraft.world.level.Level.m_142425_(Level.java:824) ~[server-1.20.1-20230612.114412-srg.jar%23316!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:lithium.mixins.json:alloc.chunk_random.WorldMixin,pl:mixin:APP:lithium.mixins.json:block.hopper.WorldMixin,pl:mixin:APP:lithium.mixins.json:entity.collisions.intersection.WorldMixin,pl:mixin:APP:lithium.mixins.json:util.block_entity_retrieval.WorldMixin,pl:mixin:APP:lithium.mixins.json:util.block_tracking.block_listening.WorldMixin,pl:mixin:APP:lithium.mixins.json:world.block_entity_ticking.sleeping.WorldMixin,pl:mixin:APP:lithium.mixins.json:world.chunk_access.WorldMixin,pl:mixin:APP:lithium.mixins.json:world.inline_block_access.WorldMixin,pl:mixin:APP:lithium.mixins.json:world.inline_height.WorldMixin,pl:mixin:A,re:mixin,pl:accesstransformer:B}
	at net.minecraft.world.level.block.entity.ContainerOpenersCounter.m_155457_(ContainerOpenersCounter.java:91) ~[server-1.20.1-20230612.114412-srg.jar%23316!/:?] {re:classloading}
	at net.minecraft.world.level.block.entity.ContainerOpenersCounter.m_155476_(ContainerOpenersCounter.java:95) ~[server-1.20.1-20230612.114412-srg.jar%23316!/:?] {re:classloading}
	at noobanidus.mods.lootr.block.entities.LootrBarrelBlockEntity.recheckOpen(LootrBarrelBlockEntity.java:280) ~[lootr-1.20-0.7.31.76.jar%23272!/:0.7.31.76] {re:classloading}
	at noobanidus.mods.lootr.block.LootrBarrelBlock.m_213897_(LootrBarrelBlock.java:83) ~[lootr-1.20-0.7.31.76.jar%23272!/:0.7.31.76] {re:classloading}
	at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_222963_(BlockBehaviour.java:759) ~[server-1.20.1-20230612.114412-srg.jar%23316!/:?] {re:mixin,re:classloading,pl:mixin:APP:lithium.mixins.json:ai.pathing.AbstractBlockStateMixin,pl:mixin:APP:lithium.mixins.json:util.block_tracking.AbstractBlockStateMixin,pl:mixin:APP:vampiricageing.mixins.json:BlockBehaviourMixin,pl:mixin:APP:ferritecore.blockstatecache.mixin.json:BlockStateBaseMixin,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.m_184112_(ServerLevel.java:781) ~[server-1.20.1-20230612.114412-srg.jar%23316!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendisland.mixins.json:ServerLevelMixin,pl:mixin:APP:lithium.mixins.json:alloc.chunk_random.ServerWorldMixin,pl:mixin:APP:lithium.mixins.json:chunk.entity_class_groups.ServerWorldAccessor,pl:mixin:APP:lithium.mixins.json:entity.inactive_navigations.ServerWorldMixin,pl:mixin:APP:lithium.mixins.json:profiler.ServerWorldMixin,pl:mixin:APP:lithium.mixins.json:util.entity_movement_tracking.ServerWorldAccessor,pl:mixin:APP:lithium.mixins.json:world.block_entity_ticking.sleeping.ServerWorldMixin,pl:mixin:APP:betterdeserttemples.mixins.json:ServerLevelMixin,pl:mixin:APP:betterendisland.mixins.json:EndergeticExpansionMixins,pl:mixin:A,re:mixin,pl:accesstransformer:B}
	at net.minecraft.world.ticks.LevelTicks.m_193272_(LevelTicks.java:215) ~[server-1.20.1-20230612.114412-srg.jar%23316!/:?] {re:classloading}
	at net.minecraft.world.ticks.LevelTicks.m_193225_(LevelTicks.java:98) ~[server-1.20.1-20230612.114412-srg.jar%23316!/:?] {re:classloading}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:378) ~[server-1.20.1-20230612.114412-srg.jar%23316!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:betterendisland.mixins.json:ServerLevelMixin,pl:mixin:APP:lithium.mixins.json:alloc.chunk_random.ServerWorldMixin,pl:mixin:APP:lithium.mixins.json:chunk.entity_class_groups.ServerWorldAccessor,pl:mixin:APP:lithium.mixins.json:entity.inactive_navigations.ServerWorldMixin,pl:mixin:APP:lithium.mixins.json:profiler.ServerWorldMixin,pl:mixin:APP:lithium.mixins.json:util.entity_movement_tracking.ServerWorldAccessor,pl:mixin:APP:lithium.mixins.json:world.block_entity_ticking.sleeping.ServerWorldMixin,pl:mixin:APP:betterdeserttemples.mixins.json:ServerLevelMixin,pl:mixin:APP:betterendisland.mixins.json:EndergeticExpansionMixins,pl:mixin:A,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:1158) ~[server-1.20.1-20230612.114412-srg.jar%23316!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A,re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraftserver}
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:341) ~[server-1.20.1-20230612.114412-srg.jar%23316!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:mixins/common/nochatreports.mixins.json:server.MixinDedicatedServer,pl:mixin:A,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:1074) ~[server-1.20.1-20230612.114412-srg.jar%23316!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A,re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraftserver}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:904) ~[server-1.20.1-20230612.114412-srg.jar%23316!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A,re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraftserver}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:281) ~[server-1.20.1-20230612.114412-srg.jar%23316!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A,re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_minecraftserver}
	at java.lang.Thread.run(Thread.java:840) [?:?] {re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin,re:mixin}
```

# System Details
```
Minecraft Version: 1.20.1
Minecraft Version ID: 1.20.1
Operating System: Linux (amd64) version 4.18.0-513.5.1.el8_9.x86_64
Java Version: 17.0.10, Eclipse Adoptium
Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
Memory: 3615576632 bytes (3448 MiB) / 8589934592 bytes (8192 MiB) up to 8589934592 bytes (8192 MiB)
CPUs: 2
Processor Vendor: AuthenticAMD
Processor Name: AMD Ryzen 7 5800X 8-Core Processor
Identifier: AuthenticAMD Family 25 Model 33 Stepping 0
Microarchitecture: Zen 3
Number of physical packages: 1
Number of physical CPUs: 8
Number of logical CPUs: 16
Virtual memory max (MB): 81560.46
Virtual memory used (MB): 93240.73
Swap memory total (MB): 17407.99
Swap memory used (MB): 3180.71
JVM Flags: 27 total; -XX:ActiveProcessorCount=2 -Xmx8192M -Xms5324M -Xms8192M -Xmx8192M -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20
```

**Comment by noobanidus** [comment]
Now that is an unexpected error. When I was updating this code to myself, I considered whether or not to add a null check but thought "no, there aren't any circumstances where it can be null"...

I guess I was wrong!

**Comment by noobanidus** [comment]
The [latest version on CurseForge](https://www.curseforge.com/minecraft/mc-mods/lootr/files/5081906) for 1.20, 0.7.31.77, should have a fix for this enabled, please let me know if that solves it for you.

**Comment by lunofe** [comment]
Thanks for your attention to this, I guess this might be a weird edge case because I'm running Mohist, it's know to modify things in unpredictable ways
