### ISSUE TITLE
Crash on server

### ISSUE THREAD

**Issue by HenrikoMagnifico** [noobanidus/Lootr#312]
Sometimes when loading new chunks on a server, the server hangs up and times out. It seems to be caused by Lootr.

[Crash log](https://pastebin.com/JnNZ290r)

Using the latest version of Lootr Forge on 1.19.2.

**Comment by noobanidus** [comment]
Thanks for the report! This is a bit frustrating and I'm not entirely sure what's triggering it -- I'm hopeful it's just some redundant code from previous versions that I can remove, but it may have to do with the recent changes I made to the block entity ticker to make it compatible with chunk generation mods.

**Comment by noobanidus** [comment]
If it's not too much trouble and you get a chance, would you be able to try the previous version of Lootr for 1.19.2 Forge, [0.4.25.67](https://www.curseforge.com/minecraft/mc-mods/lootr/files/5082102)?

**Comment by noobanidus** [comment]
~~Would you actually be able to try this build: [lootr-1.19-0.4.26.68.jar.zip](https://github.com/LootrMinecraft/Lootr/files/14610489/lootr-1.19-0.4.26.68.jar.zip)?~~

~~You'll need to rename it from `.jar.zip` to `.jar`. It's the same version and should only need to be installed on the server. In theory this should fix it. I am also still curious if you get the error with the previous version.~~

~~What appears to be happening here is that a chest that is being replaced is very near to a chunk border (1 block away); when the chest is replaced, it updates the redstone signal of adjacent blocks, checking that those positions have a generated chunk at them.~~

~~Unfortunately, it then checks the additional positions to see if they conduct redstone and, if they do, signals to the next block in the chain -- without checking to see if that block is in a generated chunk. Hence, it can force chunks to load and cause the server thread to block.~~

~~The previous version of Lootr used a chunk cache that stored the positions of all generated chunks and avoided converting blocks when a 5x5 grid (with the original chunk in the center) wasn't fully generated. I removed this in favor of just using the provider's `hasChunk` method, which I hoped was identical, but it seems that may not be the case.~~

This would potentially break redstone so I'm going to go with another solution instead. I'll do a release for that shortly.

**Comment by HenrikoMagnifico** [comment]
Thanks! I'll try it tonight.

**Comment by noobanidus** [comment]
Did you get a chance to try this new version? If not, please don't worry, as someone pointed out my mixin may cause issues with redstone. I'm just going to fall back on the previous behaviour and release a new version shortly.

**Comment by noobanidus** [comment]
This is now released for 1.20 and 1.19.0/1.19.1/1.19.2 for Forge.

**Comment by noobanidus** [comment]
Now available for Forge for 1.18.2.

**Comment by Pinkietron** [comment]
I am experiencing Lootr Server Crashes on Fabric 1.20.1

`[31.03 19:09:11] [Server] Crash report:
[31.03 19:09:11] [Server] ---- Minecraft Crash Report ----
[31.03 19:09:11] [Server] // This is a token for free hug. Redeem at your nearest Mojangsta: [~~HUG~~]
[31.03 19:09:11] [Server] Time2024-03-31 19:09:11
[31.03 19:09:11] [Server] DescriptionWatching Server
[31.03 19:09:11] [Server] java.lang.ErrorWatchdog
[31.03 19:09:11] [Server] 	at java.base@17.0.8/jdk.internal.misc.Unsafe.park(Native Method)
[31.03 19:09:11] [Server] 	at java.base@17.0.8/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252)
[31.03 19:09:11] [Server] 	at net.minecraft.class_1255.method_20813(class_1255.java:151)
[31.03 19:09:11] [Server] 	at net.minecraft.class_1255.method_18857(class_1255.java:141)
[31.03 19:09:11] [Server] 	at net.minecraft.class_3215.getChunkBlocking(class_3215.java:2788)
[31.03 19:09:11] [Server] 	at net.minecraft.class_3215.method_12121(class_3215.java:2684)
[31.03 19:09:11] [Server] 	at net.minecraft.class_1937.method_8402(class_1937.java:204)
[31.03 19:09:11] [Server] 	at net.minecraft.class_1937.method_22350(class_1937.java:8549)
[31.03 19:09:11] [Server] 	at net.minecraft.class_1937.method_8500(class_1937.java:8544)
[31.03 19:09:11] [Server] 	at net.minecraft.class_1937.method_8321(class_1937.java:559)
[31.03 19:09:11] [Server] 	at net.zestyblaze.lootr.blocks.entities.TileTicker.serverTick(TileTicker.java:83)
[31.03 19:09:11] [Server] 	at net.zestyblaze.lootr.registry.LootrEventsInit.lambda$registerEvents$2(LootrEventsInit.java:35)
[31.03 19:09:11] [Server] 	at net.zestyblaze.lootr.registry.LootrEventsInit$$Lambda$9206/0x00007f6569346768.onEndTick(Unknown Source)
[31.03 19:09:11] [Server] 	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerTickEvents.lambda$static$2(ServerTickEvents.java:43)
[31.03 19:09:11] [Server] 	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerTickEvents$$Lambda$3876/0x00007f6568ad23a8.onEndTick(Unknown Source)
[31.03 19:09:11] [Server] 	at net.minecraft.server.MinecraftServer.handler$ceh002$fabric-lifecycle-events-v1$onEndTick(MinecraftServer.java:7362)
[31.03 19:09:11] [Server] 	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:847)
[31.03 19:09:11] [Server] 	at net.minecraft.server.MinecraftServer.handler$bel000$carpet$modifiedRunLoop(MinecraftServer.java:12442)
[31.03 19:09:11] [Server] 	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:650)
[31.03 19:09:11] [Server] 	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
[31.03 19:09:11] [Server] 	at net.minecraft.server.MinecraftServer$$Lambda$15484/0x00007f6569b42db8.run(Unknown Source)
[31.03 19:09:11] [Server] 	at java.base@17.0.8/java.lang.Thread.run(Thread.java:833)
[31.03 19:09:11] [Server] A detailed walkthrough of the error, its code path and all known details is as follows:
[31.03 19:09:11] [Server] ---------------------------------------------------------------------------------------
[31.03 19:09:11] [Server] -- Head --
[31.03 19:09:11] [Server] ThreadServer Watchdog
[31.03 19:09:11] [Server] Stacktrace:
[31.03 19:09:11] [Server] 	at java.base@17.0.8/jdk.internal.misc.Unsafe.park(Native Method)
[31.03 19:09:11] [Server] 	at java.base@17.0.8/java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:252)
[31.03 19:09:11] [Server] 	at net.minecraft.class_1255.method_20813(class_1255.java:151)
[31.03 19:09:11] [Server] 	at net.minecraft.class_1255.method_18857(class_1255.java:141)
[31.03 19:09:11] [Server] 	at net.minecraft.class_3215.getChunkBlocking(class_3215.java:2788)
[31.03 19:09:11] [Server] 	at net.minecraft.class_3215.method_12121(class_3215.java:2684)
[31.03 19:09:11] [Server] 	at net.minecraft.class_1937.method_8402(class_1937.java:204)
[31.03 19:09:11] [Server] 	at net.minecraft.class_1937.method_22350(class_1937.java:8549)
[31.03 19:09:11] [Server] 	at net.minecraft.class_1937.method_8500(class_1937.java:8544)
[31.03 19:09:11] [Server] 	at net.minecraft.class_1937.method_8321(class_1937.java:559)
[31.03 19:09:11] [Server] 	at net.zestyblaze.lootr.blocks.entities.TileTicker.serverTick(TileTicker.java:83)
[31.03 19:09:11] [Server] 	at net.zestyblaze.lootr.registry.LootrEventsInit.lambda$registerEvents$2(LootrEventsInit.java:35)
[31.03 19:09:11] [Server] 	at net.zestyblaze.lootr.registry.LootrEventsInit$$Lambda$9206/0x00007f6569346768.onEndTick(Unknown Source)
[31.03 19:09:11] [Server] 	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerTickEvents.lambda$static$2(ServerTickEvents.java:43)
[31.03 19:09:11] [Server] 	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerTickEvents$$Lambda$3876/0x00007f6568ad23a8.onEndTick(Unknown Source)
[31.03 19:09:11] [Server] 	at net.minecraft.server.MinecraftServer.handler$ceh002$fabric-lifecycle-events-v1$onEndTick(MinecraftServer.java:7362)
[31.03 19:09:11] [Server] 	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:847)
[31.03 19:09:11] [Server] 	at net.minecraft.server.MinecraftServer.handler$bel000$carpet$modifiedRunLoop(MinecraftServer.java:12442)
[31.03 19:09:11] [Server] 	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:650)
[31.03 19:09:11] [Server] 	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
[31.03 19:09:11] [Server] -- Thread Dump --
[31.03 19:09:11] [Server] Details:
[31.03 19:09:11] [Server] 	Threads"Reference Handler" daemon prio=10 Id=2 RUNNABLE
[31.03 19:09:11] [Server] 	at java.base@17.0.8/java.lang.ref.Reference.waitForReferencePendingList(Native Method)
[31.03 19:09:11] [Server] 	at java.base@17.0.8/java.lang.ref.Reference.processPendingReferences(Reference.java:253)
[31.03 19:09:11] [Server] 	at java.base@17.0.8/java.lang.ref.Reference$ReferenceHandler.run(Reference.java:215)
[31.03 19:09:11] [Server] "Finalizer" daemon prio=Id=3 WAITING on java.lang.ref.ReferenceQueue$Lock@14756236
[31.03 19:09:11] [Server] 	at java.base@17.0.8/java.lang.Object.wait(Native Method)
[31.03 19:09:11] [Server] 	-  waiting on java.lang.ref.ReferenceQueue$Lock@14756236
[31.03 19:09:11] [Server] 	at java.base@17.0.8/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:155)
[31.03 19:09:11] [Server] 	at java.base@17.0.8/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:176)
[31.03 19:09:11] [Server] 	at java.base@17.0.8/java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:172)
[31.03 19:09:11] [Server] "Signal Dispatcher" daemon prio=Id=4 RUNNABLE
[31.03 19:09:11] [Server] "Common-Cleaner" daemon prio=Id=23 TIMED_WAITING on java.lang.ref.ReferenceQueue$Lock@7efafaa7
[31.03 19:09:11] [Server] 	at java.base@17.0.8/java.lang.Object.wait(Native Method)
[31.03 19:09:11] [Server] 	-  waiting on java.lang.ref.ReferenceQueue$Lock@7efafaa7
[31.03 19:09:11] [Server] 	at java.base@17.0.8/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:155)
[31.03 19:09:11] [Server] 	at java.base@17.0.8/jdk.internal.ref.CleanerImpl.run(CleanerImpl.java:140)
[31.03 19:09:11] [Server] 	at java.base@17.0.8/java.lang.Thread.run(Thread.java:833)
[31.03 19:09:11] [Server] 	at java.base@17.0.8/jdk.internal.misc.InnocuousThread.run(InnocuousThread.java:162)
[31.03 19:09:11] [Server] "Notification Thread" daemon prio=Id=24 RUNNABLE
[31.03 19:09:11] [Server] "JNA Cleaner" daemon prio=Id=64 WAITING on java.lang.ref.ReferenceQueue$Lock@6104fbfd
[31.03 19:09:11] [Server] 	at java.base@17.0.8/java.lang.Object.wait(Native Method)
[31.03 19:09:11] [Server] 	-  waiting on java.lang.ref.ReferenceQueue$Lock@6104fbfd
[31.03 19:09:11] [Server] 	at java.base@17.0.8/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:155)
[31.03 19:09:11] [Server] 	at java.base@17.0.8/java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:176)
[31.03 19:09:11] [Server] 	at com.sun.jna.internal.Cleaner$1.run(Cleaner.java:58)
[31.03 19:09:11] [Server] "Thread-2" daemon prio=Id=65 TIMED_WAITING
[31.03 19:09:11] [Server] 	at java.base@17.0.8/jdk.internal.misc.Unsafe.park(Native Method)`

**Comment by ColdStoneSys** [comment]
I am getting server crashes due to lootr as well on 1.20.1 Fabric
This always happens whenever i try to preload chunks using chunky

[crashreport.txt](https://github.com/LootrMinecraft/Lootr/files/14817884/crashreport.txt)

**Comment by noobanidus** [comment]
@Pinkietron Unfortunately, due to the number of bugs discovered recently, I haven't managed to port the changes for Chunky to Fabric. Please disable Lootr while using the Chunky pregenerator -- there is a disable option in the configuration -- and then re-enable once generation is complete.
