### ISSUE TITLE
Can't add mod dimension to dimension_blacklist

### ISSUE THREAD

**Issue by Sh4itan** [noobanidus/Lootr#72]
I'm unable to add the dimension for [Dimensional Dungeons](https://www.curseforge.com/minecraft/mc-mods/dimensional-dungeons) to my blacklist in config. according to mod author the dimension is "dimdungeons:dungeon_dinemsion

Server crashes with error log:

```
	Mod File: lootr-1.18-0.0.12.37.jar
	Failure message: Lootr (lootr) has failed to load correctly
		java.lang.reflect.InvocationTargetException: null
	Mod Version: 0.0.12.36
	Mod Issue URL: https://github.com/noobanidus/Lootr/issues
	Exception message: com.electronwill.nightconfig.core.io.ParsingException: Invalid value: dimdungeons:dungeon_dimension
Stacktrace:
	at com.electronwill.nightconfig.toml.ValueParser.parseNumber(ValueParser.java:102) ~[toml-3.6.4.jar%2343!:?] {}
	at com.electronwill.nightconfig.toml.ValueParser.parse(ValueParser.java:64) ~[toml-3.6.4.jar%2343!:?] {}
	at com.electronwill.nightconfig.toml.ArrayParser.parse(ArrayParser.java:32) ~[toml-3.6.4.jar%2343!:?] {}
	at com.electronwill.nightconfig.toml.ValueParser.parse(ValueParser.java:33) ~[toml-3.6.4.jar%2343!:?] {}
	at com.electronwill.nightconfig.toml.ValueParser.parse(ValueParser.java:69) ~[toml-3.6.4.jar%2343!:?] {}
	at com.electronwill.nightconfig.toml.TableParser.parseNormal(TableParser.java:57) ~[toml-3.6.4.jar%2343!:?] {}
	at com.electronwill.nightconfig.toml.TomlParser.parse(TomlParser.java:44) ~[toml-3.6.4.jar%2343!:?] {}
	at com.electronwill.nightconfig.toml.TomlParser.parse(TomlParser.java:37) ~[toml-3.6.4.jar%2343!:?] {}
	at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:113) ~[core-3.6.4.jar%2342!:?] {}
	at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:219) ~[core-3.6.4.jar%2342!:?] {}
	at com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:202) ~[core-3.6.4.jar%2342!:?] {}
	at com.electronwill.nightconfig.core.file.WriteSyncFileConfig.load(WriteSyncFileConfig.java:73) ~[core-3.6.4.jar%2342!:?] {}
	at com.electronwill.nightconfig.core.file.AutosaveCommentedFileConfig.load(AutosaveCommentedFileConfig.java:85) ~[core-3.6.4.jar%2342!:?] {}
	at noobanidus.mods.lootr.config.ConfigManager.loadConfig(ConfigManager.java:101) ~[lootr-1.18-0.0.12.37.jar%23105!:0.0.12.37] {re:mixin,re:classloading}
	at noobanidus.mods.lootr.Lootr.<init>(Lootr.java:59) ~[lootr-1.18-0.0.12.37.jar%23105!:0.0.12.37] {re:classloading}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:81) ~[javafmllanguage-1.18.1-39.0.9.jar%23146!:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[fmlcore-1.18.1-39.0.9.jar%23145!:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}
```

as i can't blacklist barrels, i need to blacklist the mod, which sadly doesn't work :/

**Comment by noobanidus** [comment]
Can you upload a copy of your configuration file?

EDIT: I'm not sure why it's trying to parse numbers, I'm going to assume that there's some sort of formatting error. It should look like `["dimdungeons:dungeon_dimension"]`.

Alternately, that might not be the actual dimension name. If you launch Minecraft and use `/execute in` you'll be able to tab through all of the relevant dimensions.

EDIT: Actually, looking at it again, it's crashing before it even gets to the validator or trying to parse into a ResourceKey. There's definitely something wrong with your formatting, and I'll need to see a copy of the configuration file to understand what.

**Comment by Sh4itan** [comment]
Yeah, i seem to be dumb...

Being an IT guy myself I should've known to put the array values in quotations... yikes. Works like a charm now!

Thanks for the very fast answer, tho!

PS: you might want to put the quotations in your examples, too - for dummies like me :'D

**Comment by noobanidus** [comment]
That's really my bad. I want to convert to a sectioned, more thoroughly-documented system but I'm not sure how to ensure backwards compatibility. :/ Glad that sorted it though!
