### ISSUE TITLE
Lootr failed to load correctly

### ISSUE THREAD

**Issue by ellbristow** [noobanidus/Lootr#78]
Getting this every time I launch the game. Tried with multiple versions of Forge.

![image](https://user-images.githubusercontent.com/1309054/151659061-decddb89-3add-4d46-85f2-1db520786e57.png)

Crash Log:

---- Minecraft Crash Report ----
// Why did you do that?

Time: 1/29/22, 12:21 PM
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:69) ~[forge-1.18.1-39.0.63-universal.jar%23150!/:?] {re:classloading}
	at net.minecraftforge.client.loading.ClientModLoader.completeModLoading(ClientModLoader.java:183) ~[forge-1.18.1-39.0.63-universal.jar%23150!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$new$1(Minecraft.java:553) ~[client-1.18.1-20211210.034407-srg.jar%23146!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.Util.m_137521_(Util.java:409) ~[client-1.18.1-20211210.034407-srg.jar%23146!/:?] {re:classloading}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:547) ~[client-1.18.1-20211210.034407-srg.jar%23146!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.LoadingOverlay.m_6305_(LoadingOverlay.java:135) ~[client-1.18.1-20211210.034407-srg.jar%23146!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:875) ~[client-1.18.1-20211210.034407-srg.jar%23146!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1040) ~[client-1.18.1-20211210.034407-srg.jar%23146!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:660) ~[client-1.18.1-20211210.034407-srg.jar%23146!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:flywheel.mixins.json:ShaderCloseMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.client.MinecraftAccess,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.1-20211210.034407-srg.jar%23146!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:45) ~[fmlloader-1.18.1-39.0.63.jar%2323!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.0.jar%235!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-1.0.1.jar:?] {}
-- MOD lootr --
Details:
	Caused by 0: java.lang.RuntimeException: java.lang.ClassNotFoundException: noobanidus.mods.lootr.event.HandleChunk
		at net.minecraftforge.fml.javafmlmod.AutomaticEventSubscriber.lambda$inject$6(AutomaticEventSubscriber.java:80) ~[javafmllanguage-1.18.1-39.0.63.jar%23148!/:?] {}
		at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?] {re:mixin}
		at net.minecraftforge.fml.javafmlmod.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:62) ~[javafmllanguage-1.18.1-39.0.63.jar%23148!/:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:91) ~[javafmllanguage-1.18.1-39.0.63.jar%23148!/:?] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[fmlcore-1.18.1-39.0.63.jar%23147!/:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

	Mod File: lootr-1.18-0.1.14.45.jar
	Failure message: Lootr (lootr) has failed to load correctly
		java.lang.RuntimeException: java.lang.ClassNotFoundException: noobanidus.mods.lootr.event.HandleChunk
	Mod Version: 0.1.14.45
	Mod Issue URL: https://github.com/noobanidus/Lootr/issues
	Exception message: java.lang.ClassNotFoundException: noobanidus.mods.lootr.event.HandleChunk
Stacktrace:
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135) ~[securejarhandler-1.0.1.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	at java.lang.Class.forName0(Native Method) ~[?:?] {re:mixin}
	at java.lang.Class.forName(Class.java:467) ~[?:?] {re:mixin}
	at net.minecraftforge.fml.javafmlmod.AutomaticEventSubscriber.lambda$inject$6(AutomaticEventSubscriber.java:75) ~[javafmllanguage-1.18.1-39.0.63.jar%23148!/:?] {}
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?] {re:mixin}
	at net.minecraftforge.fml.javafmlmod.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:62) ~[javafmllanguage-1.18.1-39.0.63.jar%23148!/:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:91) ~[javafmllanguage-1.18.1-39.0.63.jar%23148!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[fmlcore-1.18.1-39.0.63.jar%23147!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1074171392 bytes (1024 MiB) / 2338324480 bytes (2230 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 1600 Six-Core Processor            
	Identifier: AuthenticAMD Family 23 Model 1 Stepping 1
	Microarchitecture: Zen
	Frequency (GHz): 3.19
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce GTX 1660
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2184
	Graphics card #0 versionInfo: DriverVersion=27.21.14.6259
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: DDR4
	Memory slot #2 capacity (MB): 8192.00
	Memory slot #2 clockSpeed (GHz): 2.13
	Memory slot #2 type: DDR4
	Memory slot #3 capacity (MB): 8192.00
	Memory slot #3 clockSpeed (GHz): 2.13
	Memory slot #3 type: DDR4
	Virtual memory max (MB): 47546.28
	Virtual memory used (MB): 31813.04
	Swap memory total (MB): 14848.00
	Swap memory used (MB): 1588.95
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx4096m -Xms256m
	ModLauncher: 9.1.0+9.1.0+main.6690ee51
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		javafml@null
	Mod List: 
		tetra-1.18.1-4.5.0.jar                            |Tetra                         |tetra                         |4.5.0               |COMMON_SET|Manifest: NOSIGNATURE
		inventorysorter-1.18-19.0.0.jar                   |Simple Inventory Sorter       |inventorysorter               |19.0.0              |COMMON_SET|Manifest: NOSIGNATURE
		no_null_processors_forge-2.0.2+1.18.1.jar         |No Null Processors            |no_null_processors            |2.0.2+1.18.1        |COMMON_SET|Manifest: NOSIGNATURE
		torchslabmod-1.18.1_v1.7.5.jar                    |Torch Slab Mod                |torchslabmod                  |1.7.5               |COMMON_SET|Manifest: NOSIGNATURE
		jei-1.18.1-9.2.1.69.jar                           |Just Enough Items             |jei                           |9.2.1.69            |COMMON_SET|Manifest: NOSIGNATURE
		scannable-1.18.1-forge-1.7.6+da03abb.jar          |Scannable                     |scannable                     |1.7.6               |COMMON_SET|Manifest: NOSIGNATURE
		modnametooltip-1.18.1-1.18.0.jar                  |Mod Name Tooltip              |modnametooltip                |1.18.0              |COMMON_SET|Manifest: NOSIGNATURE
		waystones-forge-1.18.1-9.0.3.jar                  |Waystones                     |waystones                     |9.0.3               |COMMON_SET|Manifest: NOSIGNATURE
		ForgeEndertech-1.18.1-8.0.0.0-build.0040.jar      |ForgeEndertech                |forgeendertech                |08.0.0.0            |COMMON_SET|Manifest: NOSIGNATURE
		mcw-paintings-1.0.2-mc1.18.1.jar                  |Macaw's Paintings             |mcwpaintings                  |1.0.2               |COMMON_SET|Manifest: NOSIGNATURE
		journeymap-1.18.1-5.8.0beta11.jar                 |Journeymap                    |journeymap                    |5.8.0beta11         |COMMON_SET|Manifest: NOSIGNATURE
		cookingforblockheads-forge-1.18.1-11.1.0.jar      |CookingForBlockheads          |cookingforblockheads          |11.1.0              |COMMON_SET|Manifest: NOSIGNATURE
		Controlling-forge-1.18.1-9.0.11.jar               |Controlling                   |controlling                   |9.0.11              |COMMON_SET|Manifest: NOSIGNATURE
		comforts-forge-1.18-5.0.0.1.jar                   |Comforts                      |comforts                      |1.18-5.0.0.1        |COMMON_SET|Manifest: NOSIGNATURE
		NaturesCompass-1.18.1-1.9.4-forge.jar             |Nature's Compass              |naturescompass                |1.18.1-1.9.4-forge  |COMMON_SET|Manifest: NOSIGNATURE
		configured-1.5.1-1.18.1.jar                       |Configured                    |configured                    |1.5.1               |COMMON_SET|Manifest: NOSIGNATURE
		feature_nbt_deadlock_be_gone_forge-1.0.0+1.18.1.ja|Feature NBT Deadlock Be Gone  |feature_nbt_deadlock_be_gone  |1.0.0+1.18.1        |COMMON_SET|Manifest: NOSIGNATURE
		Shrink-1.18.1-1.3.0.jar                           |Shrink                        |shrink                        |1.3.0               |COMMON_SET|Manifest: NOSIGNATURE
		sophisticatedbackpacks-1.18.1-3.15.1.505.jar      |Sophisticated Backpacks       |sophisticatedbackpacks        |1.18.1-3.15.1.505   |COMMON_SET|Manifest: NOSIGNATURE
		balm-2.4.1+0.jar                                  |Balm                          |balm                          |2.4.1+0             |COMMON_SET|Manifest: NOSIGNATURE
		randomium-1.18.1-1.8.jar                          |Randomium                     |randomium                     |1.18.1-1.8          |COMMON_SET|Manifest: NOSIGNATURE
		JustEnoughResources-1.18.1-0.13.1.141.jar         |Just Enough Resources         |jeresources                   |0.13.1.141          |COMMON_SET|Manifest: NOSIGNATURE
		cloth-config-6.1.50-forge.jar                     |Cloth Config v4 API           |cloth_config                  |6.1.50              |COMMON_SET|Manifest: NOSIGNATURE
		forge-1.18.1-39.0.63-universal.jar                |Forge                         |forge                         |39.0.63             |COMMON_SET|Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		MmmMmmMmmMmm-1.18-1.5.0.jar                       |MmmMmmMmmMmm                  |dummmmmmy                     |1.18-1.5.0          |COMMON_SET|Manifest: NOSIGNATURE
		supplementaries-1.18.1-1.1.11.jar                 |Supplementaries               |supplementaries               |1.1.11              |COMMON_SET|Manifest: NOSIGNATURE
		refinedstorage-1.10.0.jar                         |Refined Storage               |refinedstorage                |1.10.0              |COMMON_SET|Manifest: NOSIGNATURE
		selene-1.18-1.12.0.jar                            |Selene                        |selene                        |1.18-1.12.0         |COMMON_SET|Manifest: NOSIGNATURE
		replantingcrops_1.18.1-2.6.jar                    |Replanting Crops              |replantingcrops               |2.6                 |COMMON_SET|Manifest: NOSIGNATURE
		client-1.18.1-20211210.034407-srg.jar             |Minecraft                     |minecraft                     |1.18.1              |COMMON_SET|Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		repurposed_structures_forge-4.2.4+1.18.1.jar      |Repurposed Structures         |repurposed_structures         |4.2.4+1.18.1        |COMMON_SET|Manifest: NOSIGNATURE
		EnchantmentDescriptions-Forge-1.18.1-9.0.11.jar   |EnchantmentDescriptions       |enchdesc                      |9.0.11              |COMMON_SET|Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		theoneprobe-1.18-5.0.3.jar                        |The One Probe                 |theoneprobe                   |1.18-5.0.3          |COMMON_SET|Manifest: NOSIGNATURE
		MouseTweaks-forge-mc1.18-2.21.jar                 |Mouse Tweaks                  |mousetweaks                   |2.21                |COMMON_SET|Manifest: NOSIGNATURE
		Compressium-1.4.0-build.4+mc1.18.jar              |Compressium                   |compressium                   |1.4.0-build.4+mc1.18|COMMON_SET|Manifest: NOSIGNATURE
		ImmersiveEngineering-1.18.1-7.1.0-145.jar         |Immersive Engineering         |immersiveengineering          |1.18.1-7.1.0-145    |COMMON_SET|Manifest: 44:39:94:cf:1d:8c:be:3c:7f:a9:ee:f4:1e:63:a5:ac:61:f9:c2:87:d5:5b:d9:d6:8c:b5:3e:96:5d:8e:3f:b7
		endrem_forge-5.0.1-R-1.18.1.jar                   |End Remastered                |endrem                        |5.0-R-1.18.1        |COMMON_SET|Manifest: NOSIGNATURE
		ArmorPoser-forge-1.18.1-1.0.2.jar                 |Armor Poser                   |armorposer                    |1.0.2               |COMMON_SET|Manifest: NOSIGNATURE
		AdLods-1.18.1-5.0.0.0-build.0044.jar              |Large Ore Deposits            |adlods                        |05.0.0.0            |COMMON_SET|Manifest: NOSIGNATURE
		supermartijn642corelib-1.0.16a-mc1.18.jar         |SuperMartijn642's Core Lib    |supermartijn642corelib        |1.0.16a             |COMMON_SET|Manifest: NOSIGNATURE
		Paintings-forge-1.18.1-9.1.0.0.jar                |Paintings ++                  |paintings                     |9.1.0.0             |COMMON_SET|Manifest: NOSIGNATURE
		flywheel-forge-1.18-0.6.0.jar                     |Flywheel                      |flywheel                      |1.18-0.6.0          |COMMON_SET|Manifest: NOSIGNATURE
		create-mc1.18.1_v0.4d.jar                         |Create                        |create                        |0.4d                |COMMON_SET|Manifest: NOSIGNATURE
		createdeco-1.2.3-1.18.jar                         |Create Deco                   |createdeco                    |1.2.3-1.18          |COMMON_SET|Manifest: NOSIGNATURE
		Patchouli-1.18.1-64.jar                           |Patchouli                     |patchouli                     |1.18.1-64           |COMMON_SET|Manifest: NOSIGNATURE
		mutil-1.18.1-4.2.0.jar                            |mutil                         |mutil                         |4.2.0               |COMMON_SET|Manifest: NOSIGNATURE
		corail_woodcutter-1.18-2.2.1.jar                  |Corail Woodcutter             |corail_woodcutter             |2.2.1               |COMMON_SET|Manifest: NOSIGNATURE
		gravestone-1.18.1-1.0.1.jar                       |Gravestone Mod                |gravestone                    |1.18.1-1.0.1        |COMMON_SET|Manifest: NOSIGNATURE
		collective-1.18.1-3.8.jar                         |Collective                    |collective                    |3.8                 |COMMON_SET|Manifest: NOSIGNATURE
		JustEnoughProfessions-1.18-1.2.2.jar              |Just Enough Professions (JEP) |justenoughprofessions         |1.2.2               |COMMON_SET|Manifest: NOSIGNATURE
		StorageDrawers-1.18.1-10.1.1.jar                  |Storage Drawers               |storagedrawers                |10.1.1              |COMMON_SET|Manifest: NOSIGNATURE
		PaintingAbundancev2.jar                           |Painting Abundance            |painting_abundance            |1.0                 |COMMON_SET|Manifest: NOSIGNATURE
		buildersaddition-1.18.1-20220123a.jar             |Builders Crafts & Addition    |buildersaddition              |1.18.1-20220123a    |COMMON_SET|Manifest: NOSIGNATURE
		architectury-3.4.9.jar                            |Architectury                  |architectury                  |3.4.9               |COMMON_SET|Manifest: NOSIGNATURE
		appleskin-forge-mc1.18-2.2.0.jar                  |AppleSkin                     |appleskin                     |2.2.0               |COMMON_SET|Manifest: NOSIGNATURE
		lootr-1.18-0.1.14.45.jar                          |Lootr                         |lootr                         |0.1.14.45           |ERROR     |Manifest: NOSIGNATURE
		engineersdecor-1.18.1-1.1.19-b3.jar               |Engineer's Decor              |engineersdecor                |1.1.19-b3           |COMMON_SET|Manifest: bf:30:76:97:e4:58:41:61:2a:f4:30:d3:8f:4c:e3:71:1d:14:c4:a1:4e:85:36:e3:1d:aa:2f:cb:22:b0:04:9b
		globalxp-1.18.1-1.9.1.jar                         |Global XP                     |globalxp                      |1.9.1               |COMMON_SET|Manifest: NOSIGNATURE
		light-overlay-6.0.4-forge.jar                     |Light Overlay                 |lightoverlay                  |6.0.4               |COMMON_SET|Manifest: NOSIGNATURE
		trashcans-1.0.12-mc1.18.jar                       |Trash Cans                    |trashcans                     |1.0.12              |COMMON_SET|Manifest: NOSIGNATURE
		Aquaculture-1.18.1-2.3.2.jar                      |Aquaculture 2                 |aquaculture                   |1.18.1-2.3.2        |COMMON_SET|Manifest: NOSIGNATURE
		refinedstorageaddons-0.8.1.jar                    |Refined Storage Addons        |refinedstorageaddons          |0.8.1               |COMMON_SET|Manifest: NOSIGNATURE
		FastLeafDecay-27.2.jar                            |FastLeafDecay                 |fastleafdecay                 |27.2                |COMMON_SET|Manifest: NOSIGNATURE
		valhelsia_core-1.18.1-0.3.2.jar                   |Valhelsia Core                |valhelsia_core                |1.18.1-0.3.2        |COMMON_SET|Manifest: NOSIGNATURE
		valhelsia_structures-1.18.1-0.1.0.jar             |Valhelsia Structures          |valhelsia_structures          |1.18.1-0.1.0        |COMMON_SET|Manifest: NOSIGNATURE
		ChiselsBits-forge-1.18.1-1.2.77-universal.jar     |Chisels & bits                |chiselsandbits                |1.2.77              |COMMON_SET|Manifest: NOSIGNATURE
		veinmining-forge-1.18.1-0.16.jar                  |Vein Mining                   |veinmining                    |1.18.1-0.16         |COMMON_SET|Manifest: NOSIGNATURE
		createaddition-1.18.1-20220125a.jar               |Create Crafts & Additions     |createaddition                |1.18.1-20220125a    |COMMON_SET|Manifest: NOSIGNATURE
		BetterAdvancements-1.18.1-0.1.2.122.jar           |Better Advancements           |betteradvancements            |0.1.2.122           |COMMON_SET|Manifest: NOSIGNATURE
	Crash Report UUID: faa1ac4d-d30a-4afe-90c1-ad12bfe1c36a
	Flywheel Backend: GL33 Instanced Arrays
	FML: 39.0
	Forge: net.minecraftforge:39.0.63

**Comment by noobanidus** [comment]
Can you upload your full log file? I'm guessing that something went wrong earlier in the loading process.

EDIT: Also, in future, can you upload crash reports to https://gist.github.com and link them instead?

**Comment by ellbristow** [comment]
I've just been fiddling and realised that Curseforge had downloaded multiple copies of the mod and was trying to load them both. Not sure how this produced this error, but deleting all copies of Lootr then reinstalling it in the modpack fixed it. Apologies.

**Comment by noobanidus** [comment]
Ah, glad it was that simple!
