### ISSUE TITLE
Crashes on mohist mc1.18.1 server 

### ISSUE THREAD

**Issue by varHarrie** [noobanidus/Lootr#85]
Crashed when open the chest.

```log
java.lang.AbstractMethodError: Receiver class noobanidus.mods.lootr.data.SpecialChestInventory does not define or inherit an implementation of the resolved method 'abstract org.bukkit.inventory.InventoryHolder getOwner()' of interface net.minecraft.world.Container.
        at org.bukkit.craftbukkit.v1_18_R1.event.CraftEventFactory.callLootGenerateEvent(CraftEventFactory.java:1619) ~[forge-1.18.1-39.0.88-universal.jar%23146!/:?]
        at net.minecraft.world.level.storage.loot.LootTable.m_79123_(LootTable.java:117) ~[server-1.18.1-20211210.034407-srg.jar%23142!/:?]
        at noobanidus.mods.lootr.block.entities.LootrBarrelBlockEntity.unpackLootTable(LootrBarrelBlockEntity.java:165) ~[lootr-1.18-0.1.14.48.jar%23125!/:0.1.14.48]
        at noobanidus.mods.lootr.data.ChestData.createInventory(ChestData.java:187) ~[lootr-1.18-0.1.14.48.jar%23125!/:0.1.14.48]
        at noobanidus.mods.lootr.data.DataStorage.getInventory(DataStorage.java:156) ~[lootr-1.18-0.1.14.48.jar%23125!/:0.1.14.48]
        at noobanidus.mods.lootr.util.ChestUtil.handleLootChest(ChestUtil.java:128) ~[lootr-1.18-0.1.14.48.jar%23125!/:0.1.14.48]
        at noobanidus.mods.lootr.block.LootrBarrelBlock.m_6227_(LootrBarrelBlock.java:47) ~[lootr-1.18-0.1.14.48.jar%23125!/:0.1.14.48]
        at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60664_(BlockBehaviour.java:695) ~[server-1.18.1-20211210.034407-srg.jar%23142!/:?]
        at net.minecraft.server.level.ServerPlayerGameMode.m_7179_(ServerPlayerGameMode.java:335) ~[server-1.18.1-20211210.034407-srg.jar%23142!/:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.m_6371_(ServerGamePacketListenerImpl.java:993) ~[server-1.18.1-20211210.034407-srg.jar%23142!/:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.m_5797_(ServerboundUseItemOnPacket.java:30) ~[server-1.18.1-20211210.034407-srg.jar%23142!/:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.m_5797_(ServerboundUseItemOnPacket.java:8) ~[server-1.18.1-20211210.034407-srg.jar%23142!/:?]
        at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:24) ~[server-1.18.1-20211210.034407-srg.jar%23142!/:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.18.1-20211210.034407-srg.jar%23142!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:151) ~[server-1.18.1-20211210.034407-srg.jar%23142!/:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.18.1-20211210.034407-srg.jar%23142!/:?]
        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:839) ~[server-1.18.1-20211210.034407-srg.jar%23142!/:?]
        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:164) ~[server-1.18.1-20211210.034407-srg.jar%23142!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:125) ~[server-1.18.1-20211210.034407-srg.jar%23142!/:?]
        at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:822) ~[server-1.18.1-20211210.034407-srg.jar%23142!/:?]
        at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:816) ~[server-1.18.1-20211210.034407-srg.jar%23142!/:?]
        at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:134) ~[server-1.18.1-20211210.034407-srg.jar%23142!/:?]
        at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:802) ~[server-1.18.1-20211210.034407-srg.jar%23142!/:?]
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:746) ~[server-1.18.1-20211210.034407-srg.jar%23142!/:?]
        at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:283) ~[server-1.18.1-20211210.034407-srg.jar%23142!/:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Versions:**
Minecraft: 1.18.1
Forge: 39.0.88
Mohist: #146 (1.18.1-39.0.88)

**Comment by noobanidus** [comment]
This looks to be an issue with Mohist: `abstract org.bukkit.inventory.InventoryHolder getOwner()`

I'm not sure what can be done to support it on my end.

**Comment by noobanidus** [comment]
So, digging into it further, this appears to be an issue on Mohists's side -- or Bukkit's -- or ... somebody else's.
